### ISSUE TITLE
Console prints "Unable to find any words" and then "My guess is"

### ISSUE THREAD

**Issue by schwartzadev** [losc3571/Schottland_CSCI2275_FinalProject#4]
### Expected behavior
1. Press 1 (Add to guess)
2. Enter `a.`
3. Press 2 (Make guess)
4. Console shows "Unable to find any words"

### Actual behavior
* 1-3 from above
* Console shows:
```
Unable to find any words
My guess is 
Is this correct? Type y/n
```

**Comment by losc3571** [comment]
Fixed to not print the second two statement if there isn't a guess.
